### ISSUE TITLE
`Tx_matrix_2` is defined twice

### ISSUE THREAD

**Issue by tlestang** [NTD-Modelling-Consortium/ntd-model-trachoma#11]
First definition line [73](https://github.com/NTD-Modelling-Consortium/ntd-model-trachoma/blob/0316915ebe185de3a7dec4a34b38401893426705/trachoma/trachoma_functions.py#L73)

Second definition line [224](https://github.com/NTD-Modelling-Consortium/ntd-model-trachoma/blob/0316915ebe185de3a7dec4a34b38401893426705/trachoma/trachoma_functions.py#L224)

**Comment by mattg3004** [comment]
one deleted
